title: Michael Condon <span class="chevron right"></span>  # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PowerShell and Windows Professional, security focused with a passion for automation
  <br><br>
  <a href="https://www.linkedin.com/in/michael-condon-179148117">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
