title: > # your name (or website title) here  
        <span class="ps">$_.</span>Michael Condon 
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PowerShell and Windows Professional, I provide world-class software support for Microsoft Australia
  <br><br>
  <a href="https://www.linkedin.com/in/michael-condon-179148117">View My LinkedIn Profile</a> 
  <br><br>
  <a href="/pdf/CV.pdf">View My CV</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
